dist: xenial
language: python
cache: pip
env: # Temporarily run tests agains multiple versions of scipy
  - SCIPY_VERSION=1.2.1
  - SCIPY_VERSION=1.3.0
python:
  - "3.6"
  - "3.7"
install:
  - "pip install scipy==$SCIPY_VERSION"
  - "pip install -r requirements.txt"
  - "pip install -r requirements_tests.txt"
  - "pip install docutils"
  - "pip install -e ."
script:
  - pytest --cov=.
  - python setup.py check --restructuredtext --strict
  - rst2html.py --halt=2 README.rst >/dev/null
after_success:
  - codecov
