[build-system]
requires = ['setuptools', 'setuptools_scm', 'wheel']
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 80
skip-string-normalization = true
# Gradually remove these when there’s no PR
exclude = '^/anndata/(core/anndata|h5py/h5sparse|readwrite/write).py$'
